(defun test_json_to_list ( / )
  (load "json_util-v2.lsp")

  ;Array of 1 object
  (setq json1 "[{\"att_name0\":\"value0\",\"att_name1\":1,\"att_name2\":1,\"att_name3\":1.5},{\"att_name4\":1.0E+2,\"att_name5\":1E+2,\"att_name6\":-1,\"att_name7\":-1.5,\"att_name8\":1.0E-2},{\"att_name9\":1E-2,\"att_name10\":-1E-2}]")
  ;Array of objects
  (setq json2 "[{\"att_name0\":\"value0\",\"att_name1\":1,\"att_name2\":1,\"att_name3\":1.5,\"att_name4\":1.0E+2,\"att_name5\":1E+2,\"att_name6\":-1,\"att_name7\":-1.5,\"att_name8\":1.0E-2,\"att_name9\":1E-2,\"att_name10\":-1E-2}]")
  ;Objects with value as Array
  (setq json3 "{\"att_name0\":\"value0\",\"att_name1\":[1,1.5,1E+2,-1,-1.5,1.0E-2,1E-2,-1E-2]}")
  ;Objects with value as Array of Arrays / Values / Objects
  (setq json4 "{\"att_name0\":\"value0\",\"att_name1\":[1,[\"hola\",1E+2],1E-2,-1E-2,{\"att_name1\":\"value1\",\"att_name2\":\"value3\"},[\"a\",\"b\",1E+2]]}")
  ;https://json.org/example.html
  (setq json5 "{\"glossary\": {\"title\": \"example glossary\",\"GlossDiv\": {\"title\": \"S\",\"GlossList\": {\"GlossEntry\": {\"ID\": \"SGML\",\"SortAs\": \"SGML\",\"GlossTerm\": \"Standard Generalized Markup Language\",\"Acronym\": \"SGML\",\"Abbrev\": \"ISO 8879:1986\",\"GlossDef\": {\"para\": \"A meta-markup language, used to create markup languages such as DocBook.\",\"GlossSeeAlso\": [\"GML\", \"XML\"]},\"GlossSee\": \"markup\"}}}}}")
  (setq json6 "{\"widget\": {\"debug\": \"on\", \"window\": {\"title\": \"Sample Konfabulator Widget\", \"name\": \"main_window\", \"width\": 500, \"height\": 500}, \"image\": {\"src\": \"Images/Sun.png\",\"name\": \"sun1\", \"hOffset\": 250, \"vOffset\": 250, \"alignment\": \"center\"}, \"text\": {\"data\": \"Click Here\", \"size\": 36, \"style\": \"bold\", \"name\": \"text1\", \"hOffset\": 250, \"vOffset\": 100, \"alignment\": \"center\"}}}")

  (princ "--------------------------------------------------------------------------------------\n")
  (princ "json1 -> ") (princ json1) (princ "\n")
  (setq lst_json1 (dmc:json:json_to_list json1 T))
  (princ "list of json1 -> ")(princ lst_json1) (princ "\n")
  (princ "list of json1 without <ARRAY> Tags -> ")(princ (dmc:json:json_to_list json1 nil)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")
  (princ "json2 -> ") (princ json2) (princ "\n")
  (setq lst_json2 (dmc:json:json_to_list json2 T))
  (princ "list of json2 -> ")(princ lst_json2) (princ "\n")
  (princ "list of json2 without <ARRAY> Tags -> ")(princ (dmc:json:son_to_list json2 nil)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")
  (princ "json3 -> ") (princ json3) (princ "\n")
  (setq lst_json3 (dmc:json:json_to_list json3 T))
  (princ "list of json3 -> ")(princ lst_json3) (princ "\n")
  (princ "list of json3 without <ARRAY> Tags -> ")(princ (dmc:json:json_to_list json3 nil)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")
  (princ "json4 -> ") (princ json4) (princ "\n")
  (setq lst_json4 (dmc:json:json_to_list json4 T))
  (princ "list of json4 -> ")(princ lst_json4) (princ "\n")
  (princ "list of json4 without <ARRAY> Tags -> ")(princ (dmc:json:json_to_list json4 nil)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")
  (princ "json5 -> ") (princ json5) (princ "\n")
  (setq lst_json5 (dmc:json:json_to_list json5 T))
  (princ "list of json5 -> ")(princ lst_json5) (princ "\n")
  (princ "list of json5 without <ARRAY> Tags -> ")(princ (dmc:json:json_to_list json5 nil)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")
  (princ "json6 -> ") (princ json5) (princ "\n")
  (setq lst_json6 (dmc:json:json_to_list json6 T))
  (princ "list of json6 -> ")(princ lst_json6) (princ "\n")
  (princ "list of json6 without <ARRAY> Tags -> ")(princ (dmc:json:json_to_list json6 nil)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")

  (princ "------------------------------The lists to json---------------------------------------\n")
  (princ "json of lst_json1 -> ") (princ (dmc:json:list_to_json lst_json1)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")
  (princ "json of lst_json2 -> ") (princ (dmc:json:list_to_json lst_json2)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")
  (princ "json of lst_json3 -> ") (princ (dmc:json:list_to_json lst_json3)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")
  (princ "json of lst_json4 -> ") (princ (dmc:json:list_to_json lst_json4)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")
  (princ "json of lst_json5 -> ") (princ (dmc:json:list_to_json lst_json5)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")
  (princ "json of lst_json6 -> ") (princ (dmc:json:list_to_json lst_json6)) (princ "\n")
  (princ "--------------------------------------------------------------------------------------\n")
  (princ)
)
